# t-Test

## Reading the data

In [1]:
import pandas as pd
import numpy as np

idx = list(range(1, 31))
# idx = list(range(1, 6))

data_stat = []
data_nonstat = []
for i in idx:
    df_stat = pd.read_csv('intermediate_stat/rep_' + str(i) + '_1515211501445.csv')
#     df_stat = pd.read_csv('dummy_data/rep_' + str(i) + '_1512096105723.csv')
    df_stat['rep'] = i
    data_stat.append(df_stat)
    
    df_nonstat = pd.read_csv('intermediate_nonstat/rep_' + str(i) + '_1515211218849.csv')
    df_nonstat['rep'] = i
    data_nonstat.append(df_nonstat)

In [2]:
data_stat[0].head()

,Fictitious(Stoch),e-Greedy,FreqHist,e-Nash,Exp3,Frequentist,NoRegret,Xelnaga,Fictitious(Det),ReplyHist,Reply-Last,UCB1-Tuned,Skynet,Nash,MiniMaxQ,rep
0,-1.0,51.4,55.2,50.4,52.2,53.0,56.7,80.8,49.7,42.4,38.9,47.9,93.9,49.5,46.8,1
1,48.6,-1.0,53.1,48.4,49.7,53.3,54.4,71.6,49.3,38.1,37.8,44.8,87.2,50.0,50.1,1
2,44.8,46.9,-1.0,47.3,47.7,48.1,57.3,51.8,44.7,49.1,33.1,41.3,93.9,53.9,48.6,1
3,49.6,51.6,52.7,-1.0,49.6,55.8,53.9,62.8,49.3,46.1,50.4,52.3,65.8,50.8,48.7,1
4,47.8,50.3,52.3,50.4,-1.0,47.6,51.2,69.6,50.7,50.8,52.8,49.0,85.8,51.3,45.1,1

In [3]:
data_nonstat[0].head()

,Fictitious(Stoch),e-Greedy,Skynet,e-Nash,Exp3,Frequentist,NoRegret,Xelnaga,Fictitious(Det),ReplyHist,Reply-Last,UCB1-Tuned,FreqHist,Nash,MiniMaxQ,rep
0,-1.0,30.6,31.8,58.3,27.9,70.3,72.2,8.3,52.7,8.5,71.5,27.5,9.7,20.1,27.8,1
1,69.4,-1.0,64.3,68.8,47.9,85.2,54.2,68.2,87.0,45.2,83.5,47.5,45.9,75.3,50.8,1
2,68.2,35.7,-1.0,71.3,31.6,68.2,73.6,76.1,68.2,49.0,68.2,30.1,51.7,73.4,26.6,1
3,41.7,31.2,28.7,-1.0,24.6,82.6,38.5,30.4,42.1,26.5,76.5,29.0,31.2,39.6,22.6,1
4,72.1,52.1,68.4,75.4,-1.0,86.2,73.8,71.1,71.4,45.9,80.8,46.9,44.0,74.2,48.9,1

Combining dataframes

In [4]:
data_stat_all = pd.concat(data_stat).reset_index(drop=True).applymap(lambda v: v if v != -1 else np.nan)
data_nonstat_all = pd.concat(data_nonstat).reset_index(drop=True).applymap(lambda v: v if v != -1 else np.nan)

# showing one of the dataframes
data_stat_all.head()

,Fictitious(Stoch),e-Greedy,FreqHist,e-Nash,Exp3,Frequentist,NoRegret,Xelnaga,Fictitious(Det),ReplyHist,Reply-Last,UCB1-Tuned,Skynet,Nash,MiniMaxQ,rep
0,NaN,51.4,55.2,50.4,52.2,53.0,56.7,80.8,49.7,42.4,38.9,47.9,93.9,49.5,46.8,1
1,48.6,NaN,53.1,48.4,49.7,53.3,54.4,71.6,49.3,38.1,37.8,44.8,87.2,50.0,50.1,1
2,44.8,46.9,NaN,47.3,47.7,48.1,57.3,51.8,44.7,49.1,33.1,41.3,93.9,53.9,48.6,1
3,49.6,51.6,52.7,NaN,49.6,55.8,53.9,62.8,49.3,46.1,50.4,52.3,65.8,50.8,48.7,1
4,47.8,50.3,52.3,50.4,NaN,47.6,51.2,69.6,50.7,50.8,52.8,49.0,85.8,51.3,45.1,1

## Data stats

### Average and std

In [5]:
def calc_stats(df):
    df_avrg = df.mean()
    df_std = df.std()
    df_stats = pd.DataFrame([df_avrg, df_std], columns=df_avrg.index.values, index=['Average', 'Std'])
    return df_stats

data_stat_all_stats = calc_stats(100 - data_stat_all.drop('rep', 1))
data_nonstat_all_stats = calc_stats(100 - data_nonstat_all.drop('rep', 1))

In [6]:
data_stat_all_stats

,Fictitious(Stoch),e-Greedy,FreqHist,e-Nash,Exp3,Frequentist,NoRegret,Xelnaga,Fictitious(Det),ReplyHist,Reply-Last,UCB1-Tuned,Skynet,Nash,MiniMaxQ
Average,55.496667,51.950238,49.420000,52.275952,54.368095,52.392857,46.780952,33.670238,55.552857,56.782619,60.774524,53.002143,21.883333,49.810238,55.839286
Std,14.124675,11.112751,10.513734,5.856524,10.247257,15.498595,4.580557,15.150306,14.105804,9.989845,13.174159,12.260238,17.444135,2.281494,12.573492

In [7]:
data_nonstat_all_stats

,Fictitious(Stoch),e-Greedy,Skynet,e-Nash,Exp3,Frequentist,NoRegret,Xelnaga,Fictitious(Det),ReplyHist,Reply-Last,UCB1-Tuned,FreqHist,Nash,MiniMaxQ
Average,38.589048,63.600952,56.266429,38.547619,64.552381,22.354762,35.757143,55.342857,37.832381,67.424762,26.077381,65.559048,67.435714,43.261667,67.397857
Std,23.157122,15.243369,18.501472,16.948478,14.466675,16.856075,12.873561,26.773765,22.940486,16.308800,18.076522,10.768257,16.716501,18.805959,15.104673

## t-Test

### Calculating the means of each result (by repetition)

In [8]:
data_stat_avrg = (100 - data_stat_all).groupby('rep').mean()
data_nonstat_avrg = (100 - data_nonstat_all).groupby('rep').mean()

data_stat_avrg.head()

,Fictitious(Stoch),e-Greedy,FreqHist,e-Nash,Exp3,Frequentist,NoRegret,Xelnaga,Fictitious(Det),ReplyHist,Reply-Last,UCB1-Tuned,Skynet,Nash,MiniMaxQ
rep,,,,,,,,,,,,,,,
70,54.785714,51.621429,48.407143,52.492857,53.600000,53.000000,46.835714,31.800000,55.885714,58.035714,60.935714,52.664286,24.078571,49.992857,55.864286
71,55.864286,50.792857,48.185714,51.421429,54.542857,51.757143,46.978571,31.550000,56.057143,58.821429,60.528571,54.242857,23.735714,49.428571,56.092857
72,55.250000,51.542857,50.264286,51.257143,54.885714,52.414286,46.750000,33.950000,55.600000,56.728571,60.550000,54.864286,20.542857,49.871429,55.528571
73,55.378571,50.628571,49.028571,53.207143,54.628571,52.742857,46.928571,33.685714,55.714286,54.785714,61.814286,51.157143,24.792857,49.442857,56.064286
74,55.392857,52.871429,48.250000,52.750000,54.192857,52.271429,46.300000,31.614286,56.078571,58.528571,61.757143,53.535714,21.128571,49.300000,56.028571

### Calculatint t-Test for each agent

In [9]:
from scipy.stats import ttest_ind

t_test = dict.fromkeys(data_stat_avrg.columns.values)

for agent in data_stat_avrg.columns:
    t_test[agent] = ttest_ind(data_stat_avrg[agent], data_nonstat_avrg[agent])
    
t_test_df = pd.DataFrame(t_test, index=['t-statistic', 'p-value'])
t_test_df.head()

,Exp3,Fictitious(Det),Fictitious(Stoch),FreqHist,Frequentist,MiniMaxQ,Nash,NoRegret,Reply-Last,ReplyHist,Skynet,UCB1-Tuned,Xelnaga,e-Greedy,e-Nash
t-statistic,-7.688090e+01,6.132060e+01,6.462463e+01,-7.971496e+01,5.046511e+01,-6.136732e+01,2.427255e+01,3.689189e+01,6.572164e+01,-3.594048e+01,-9.468940e+01,-5.607692e+01,-1.165517e+02,-4.276108e+01,5.074229e+01
p-value,4.564141e-60,1.936521e-54,9.635347e-56,5.700695e-61,1.274633e-49,1.854065e-54,4.551689e-32,5.740205e-42,3.676937e-56,2.454328e-41,2.834206e-65,3.176455e-52,1.765676e-70,1.479800e-45,9.341526e-50

## Saving the result

In [10]:
t_test_df.to_csv('t-test.csv', encoding='utf-8')